config/routes.rb
Rails.application.routes.draw do

  post 'payments/create'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :users

  post 'static_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do
    resources :comments
  end

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/caroussel', to: 'static_pages#landing_page'

  root 'static_pages#index'

  # ActionCable
  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
    @products = Product.limit(3)
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(:from => @email,
      :to => 'bikeshopberlin@gmail.com',
      :subject => "A new contact form message from #{@name}",
      :body => @message).deliver_now
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About Bike Berlin</h1>

<p>best source to find used bikes in Berlin</p>
<p>Feel free to explore our products and to contact us if you come up with a question. We would like to help you to find your new bike which you are going to love while riding trough the streets of Berlin.</p>

<%= link_to 'Contact Section', contact_path %><br>

<%= link_to 'Back', products_path %>

app/views/static_pages/contact.html.erb
<h1>Contact Bike Berlin</h1>
<p>Feel free to write us a message and get in touch with us!</p>

<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you") do %>
<div class="row">
  <div class="col-md-4">
    <div class="form-group">
      <%= label_tag :name %>
      <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter your name" %>
    </div>
    <div class="form-group">
      <%= label_tag :email, "Email Address" %>
      <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter your email" %>
    </div>
    <div class="form-group">
      <%= label_tag :message %>
      <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter your message" %>
    </div>
  </div>
</div>
<%= submit_tag "Send" %>
<% end %><br><br>

<%= link_to 'About Section', about_path %><br>

<%= link_to 'Back', products_path %>

app/views/static_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>

<p><%= link_to 'Find our new featured products here', caroussel_path %></p>

<%= image_tag("hollandrad.jpg", class: "img-responsive") %>

<p>The date and time is <%= Time.now %></p>

app/views/static_pages/landing_page.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
    <center><%= image_tag(product.image_url) %></center>
      <div class="carousel-caption">
        <p><%= product.name %></p>
      </div>
    </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>

<%= link_to 'Back', products_path %>

app/views/static_pages/thank_you.html.erb
<h1>Thank you :D </h1>
<center><%= image_tag("smilebike.jpg", class: "img-responsive") %></center>
<br><br>
<div class="panel panel-default">
  <div class="panel-body">
    <strong><p>We have received your message and will get back to you as soon as posible.</strong>
    In the meantime, feel free to explore more of our <%= link_to 'products', products_path %>
    Your friends at Bike Shop Berlin.</p>
  </div>
</div>